# Generated by Django 5.0.1 on 2024-03-21 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salibchilar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
    ]
